# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopPop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopPop
  pod 'DropDown'

  target 'TopPopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TopPopUITests' do
    # Pods for testing
  end

end
